// https://en.wikibooks.org/wiki/LaTeX/Colors

// Default colors supported by LaTeX
const DEFAULT_COLORS = [
  'black',
  'blue',
  'brown',
  'cyan',
  'darkgray',
  'gray',
  'green',
  'lightgray',
  'lime',
  'magenta',
  'olive',
  'orange',
  'pink',
  'purple',
  'red',
  'teal',
  'violet',
  'white',
  'yellow'
] as const;

// Additional colors supported by dvipsnames package
const DVIPSNAMES_COLORS = [
  'Apricot',
  'Blue',
  'Brown',
  'Cerulean',
  'DarkOrchid',
  'Goldenrod',
  'Aquamarine',
  'BlueGreen',
  'BurntOrange',
  'CornflowerBlue',
  'Emerald',
  'Gray',
  'Bittersweet',
  'BlueViolet',
  'Cyan',
  'Black',
  'BrickRed',
  'CarnationPink',
  'Dandelion',
  'Fuchsia',
  'CadetBlue',
  'ForestGreen',
  'Green',
  'GreenYellow',
  'LimeGreen',
  'JungleGreen',
  'Lavender',
  'Maroon',
  'Navy Blue',
  'Orchid',
  'Mahogany',
  'Mulberry',
  'OrangeRed',
  'PineGreen',
  'Plum',
  'RawSienna',
  'Red',
  'Rhodamine',
  'RoyalBlue',
  'Salmon',
  'SeaGreen',
  'SpringGreen',
  'Tan',
  'Turquoise',
  'Violet',
  'WildStrawberry',
  'Yellow',
  'Melon',
  'OliveGreen',
  'Peach',
  'ProcessBlue',
  'RedOrange',
  'RoyalPurple',
  'Sepia',
  'TealBlue',
  'Magenta',
  'MidnightBlue',
  'Orange',
  'Periwinkle',
  'Purple',
  'RedViolet',
  'RubineRed',
  'SkyBlue',
  'Thistle',
  'VioletRed',
  'YellowGreen',
  'White',
  'YellowOrange'
] as const;

// Since we are using the dvipsnames package, we will only use the colors from that package (lowercase names would be invalid)
export type ColorDefinition = typeof DVIPSNAMES_COLORS[number];
